const statusEnum = {
    INITIATED: 'INITIATED',
    IMAGE_PROCESSED: 'IMAGE PROCESSED',
    RESPONSE_GENERATED: 'RESPONSE GENERATED',
    ERROR_IN_IMAGE_PROCESSING: 'ERROR IN IMAGE PROCESSING',
    ERROR_IN_GPT_RESPONSE: 'ERROR IN GPT RESPONSE'
}

module.exports = statusEnum;